LAYOUTS = {
    "title":            {"key": "title",            "label": "Title Slide",    "icon": "Layout"},
    "section_header":   {"key": "section_header",   "label": "Section Header", "icon": "Bookmark"},
    "bullets":          {"key": "bullets",          "label": "Bullets",         "icon": "List"},
    "two_column":       {"key": "two_column",       "label": "Two Column",      "icon": "Columns"},
    "arrow_columns":    {"key": "arrow_columns",    "label": "Arrow Columns",   "icon": "ArrowRight"},
    "image_left":       {"key": "image_left",       "label": "Image Left",      "icon": "Image"},
    "image_right":      {"key": "image_right",      "label": "Image Right",     "icon": "Image"},
    "image_with_cards": {"key": "image_with_cards", "label": "Image + Cards",   "icon": "Image"},
    "stats":            {"key": "stats",            "label": "Stats",           "icon": "BarChart"},
    "big_number":       {"key": "big_number",       "label": "Big Number",      "icon": "Hash"},
    "quote":            {"key": "quote",            "label": "Quote",           "icon": "Quote"},
    "timeline":         {"key": "timeline",         "label": "Timeline",        "icon": "GitBranch"},
    "process_steps":    {"key": "process_steps",    "label": "Process Steps",   "icon": "ListOrdered"},
    "pyramid":          {"key": "pyramid",          "label": "Pyramid",         "icon": "Triangle"},
    "comparison":       {"key": "comparison",       "label": "Comparison",      "icon": "GitFork"},
    "team":             {"key": "team",             "label": "Team",            "icon": "Users"},
    "team_image_grid":  {"key": "team_image_grid",  "label": "Team Image Grid", "icon": "Users"},
    "icon_grid":        {"key": "icon_grid",        "label": "Icon Grid",       "icon": "Grid3x3"},
    "agenda":           {"key": "agenda",           "label": "Agenda",          "icon": "ListOrdered"},
    "cta":              {"key": "cta",              "label": "Call to Action",  "icon": "Megaphone"},
    "blank":            {"key": "blank",            "label": "Blank",           "icon": "Square"},
}
